name: Build and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      image: submarine.banan4.com/ifocusit/react-next-full
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check changes
        run: |
          GITDIFF=$(git diff --name-only HEAD^ HEAD | grep -E -- 'src|public|package-lock.json' | tr -d '[:space:]')
          if [ "$GITDIFF" == "" ]; then
            echo "No code changes, skipped"
            exit 0
          fi
          echo ::set-env name=changes::true
          echo "${{ env.appName }} will be build and published"
      - name: Build docker image
        if: ${{ env.changes }}
        run: docker build -t ${{ env.image }}:latest .
        env:
          APP_GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
      - name: Publish to registry
        if: ${{ env.changes && github.event_name == 'push' }}
        run: |
          echo "docker login ${{ env.registry }} -u ${{ env.username }}"
          echo ${{ env.password }} | docker login ${{ env.registry }} -u ${{ env.username }} --password-stdin
          docker push ${{ env.image }}:latest
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: submarine.banan4.com
